version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: agritrust_db
    restart: always
    environment:
      POSTGRES_USER: agritrust_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: agritrust_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: